### ISSUE TITLE
Error not being thrown on invalid password

### ISSUE THREAD

**Issue by hari01584** [wersharks/flutter-101#16]
<img src="https://user-images.githubusercontent.com/31770598/196165544-de609c78-1e01-4e60-9b5f-46e7aa150897.jpg" height="400" />

Someone Kindly fix this issue. In flash chat app, No error being thrown when a wrong password is entered. Screen keeps loading.

**Comment by RGTechPro** [comment]
I would like to work upon this issue

**Comment by hari01584** [comment]
Assigned!
