### ISSUE TITLE
Build failed due to use of deprecated Android v1 embedding in destini-app

### ISSUE THREAD

**Issue by hari01584** [wersharks/flutter-101#24]
Build is getting failed due to android v1 embedding. Kindly change it to android v2 embedding.

![WhatsApp Image 2022-10-22 at 23 46 27](https://user-images.githubusercontent.com/31770598/197356568-434cb95a-7968-4381-8db6-70dfb34a324d.jpg)

**Comment by ananyachawla1** [comment]
I would like to take this up and fix the issue.

**Comment by hari01584** [comment]
Assigned!
