### ISSUE TITLE
Some UI Changes needed in destini-app

### ISSUE THREAD

**Issue by hari01584** [wersharks/flutter-101#26]
Someone please align the text in a nice way and also change the button style. It is difficult to read the text sometimes.

<img src="https://user-images.githubusercontent.com/31770598/197360527-77009cce-6e65-4790-89f1-9bf196c3efc4.jpg" height="400" />

**Comment by ananyachawla1** [comment]
I would like to work upon this

**Comment by hari01584** [comment]
Assigned!
